title: Which Way
author: Stazyanna
email: staz@riseup.net
description: > # this means to ignore newlines until "baseurl:"
  History, Heritage, Archaeology and Geopolitics by Staz

# social links
twitter_username: BBlaster1
github_username:  Stazyanna

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
